server:
  port: 8088
    
spring:
  # 配置文件选择(dev，pro)
  profiles:
    active: dev		#激活dev配置文件，如有重复则被dev覆盖
  # 国际化（消息源自动配置,springboot默认找出messages）
  messages:
     basename: i18n.messages
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.168.168.123:3306/test?characterEncoding=UTF-8
    username: zabbix
    password: zabbix
  resources:
    static-locations: classpath:/static/

eureka:
  #instance:
    #prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://172.168.169.189:8777/eureka/  #**eureka注册中心地址
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10 

#jasypt加密的盐值
jasypt:
  encryptor:
    password: amix



mybatis:
  #  mapper文件
  mapper-locations: mapper/*.xml
  #  实体类
  type-aliases-package: com.fallenfairy.*.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dozer:
  dozerPath: dozer